import networkx as nx
import numpy as np
from typing import List, Tuple, Set, Dict, Any, Optional
from collections import defaultdict
import random
import math

class ZHashClass:
    """
    Implementation of the Z hash class from the paper.
    h_i(x) = (f_i(x) + sum_{j=1}^c z[i][j][g_j(x)]) mod m
    
    where:
    - f_i: 2-wise independent hash functions
    - g_j: 2-universal hash functions  
    - z: random tables
    """
    
    def __init__(self, m: int, ell: int, c: int = 1, d: int = 2, 
                 universe_size: int = 2**32):
        """
        Initialize hash class Z.
        
        Args:
            m: Range of hash functions [0, m-1]
            ell: Size of g-function range
            c: Number of g-functions
            d: Number of hash functions (h_1, ..., h_d)
            universe_size: Size of universe U
        """
        self.m = m
        self.ell = ell
        self.c = c
        self.d = d
        self.universe_size = universe_size
        
        # Generate random prime for 2-wise independent hash functions
        self.prime = self._find_prime(max(m, universe_size) + 1000)
        
        # Generate random coefficients for f_i functions
        self.f_coeffs = []
        for i in range(d):
            a = random.randint(1, self.prime - 1)
            b = random.randint(0, self.prime - 1)
            self.f_coeffs.append((a, b))
        
        # Generate random coefficients for g_j functions (2-universal)
        self.g_coeffs = []
        for j in range(c):
            a = random.randint(1, self.prime - 1)
            b = random.randint(0, self.prime - 1)
            self.g_coeffs.append((a, b))
        
        # Initialize z tables
        # z[i][j][k] where i in [0, d-1], j in [0, c-1], k in [0, ell-1]
        self.z_tables = []
        for i in range(d):
            table = []
            for j in range(c):
                table.append([random.randint(0, m-1) for _ in range(ell)])
            self.z_tables.append(table)
    
    def _find_prime(self, n: int) -> int:
        """Find a prime number >= n"""
        def is_prime(num):
            if num < 2:
                return False
            for i in range(2, int(num**0.5) + 1):
                if num % i == 0:
                    return False
            return True
        
        while not is_prime(n):
            n += 1
        return n
    
    def _f_hash(self, i: int, x: int) -> int:
        """2-wise independent hash function"""
        a, b = self.f_coeffs[i]
        return (a * x + b) % self.prime % self.m
    
    def _g_hash(self, j: int, x: int) -> int:
        """2-universal hash function"""
        a, b = self.g_coeffs[j]
        return (a * x + b) % self.prime % self.ell
    
    def _h_i(self, i: int, x: int) -> int:
        """Single hash function h_i"""
        result = self._f_hash(i, x)
        for j in range(self.c):
            g_val = self._g_hash(j, x)
            result = (result + self.z_tables[i][j][g_val]) % self.m
        return result
    
    def hash_tuple(self, x: int) -> Tuple[int, ...]:
        """Return (h_1(x), ..., h_d(x))"""
        return tuple(self._h_i(i, x) for i in range(self.d))
    
    def hash_set(self, S: List[int]) -> Dict[int, Tuple[int, ...]]:
        """Hash all keys in set S"""
        return {x: self.hash_tuple(x) for x in S}
    
    def get_deficiency(self, T: List[int]) -> int:
        """
        Calculate deficiency d_T = |T| - max{|g_j(T)|}
        """
        if not T:
            return 0
        
        g_values = []
        for j in range(self.c):
            g_set = {self._g_hash(j, x) for x in T}
            g_values.append(len(g_set))
        
        return len(T) - max(g_values)
    
    def is_good(self, T: List[int]) -> bool:
        """Check if hash function is T-good (deficiency <= 1)"""
        return self.get_deficiency(T) <= 1
    
    def is_bad(self, T: List[int]) -> bool:
        """Check if hash function is T-bad (deficiency > 1)"""
        return self.get_deficiency(T) > 1
    
    def is_critical(self, T: List[int]) -> bool:
        """Check if hash function is T-critical (deficiency == 1)"""
        return self.get_deficiency(T) == 1


class RandomHashSimulator:
    """
    Simulates fully random hash functions for comparison
    """
    
    def __init__(self, m: int, d: int = 2):
        self.m = m
        self.d = d
        self.hash_map = {}
    
    def hash_tuple(self, x: int) -> Tuple[int, ...]:
        if x not in self.hash_map:
            self.hash_map[x] = tuple(random.randint(0, self.m-1) for _ in range(self.d))
        return self.hash_map[x]
    
    def hash_set(self, S: List[int]) -> Dict[int, Tuple[int, ...]]:
        return {x: self.hash_tuple(x) for x in S}


class GraphAnalyzer:
    """
    Analyzes graphs/hypergraphs generated by hash functions
    """
    
    @staticmethod
    def build_graph(S: List[int], hash_func, d: int = 2) -> nx.MultiGraph:
        """
        Build d-partite graph from hash values
        
        For d=2: bipartite graph
        For d>=3: d-partite hypergraph
        """
        if d == 2:
            # Build bipartite graph
            G = nx.MultiGraph()
            hash_values = hash_func.hash_set(S)
            
            for x, (v1, v2) in hash_values.items():
                # Vertex names: (part, value)
                G.add_edge((0, v1), (1, v2), key=x)
            
            return G
        
        else:
            # For d>=3, we use a special graph structure
            # where each edge connects d vertices
            return GraphAnalyzer._build_hypergraph(S, hash_func, d)
    
    @staticmethod
    def _build_hypergraph(S: List[int], hash_func, d: int) -> nx.MultiGraph:
        """
        Build d-partite hypergraph representation
        """
        G = nx.MultiGraph()
        hash_values = hash_func.hash_set(S)
        
        # Create vertices
        for part in range(d):
            for v in range(hash_func.m):
                G.add_node((part, v))
        
        # Add hyperedges as cliques (approximation for visualization)
        for x, values in hash_values.items():
            vertices = [(i, values[i]) for i in range(d)]
            for i in range(d):
                for j in range(i+1, d):
                    G.add_edge(vertices[i], vertices[j], key=x)
        
        return G
    
    @staticmethod
    def find_connected_components(G: nx.Graph) -> List[Set[int]]:
        """Find connected components of graph"""
        return list(nx.connected_components(G))
    
    @staticmethod
    def is_mog_graph(G: nx.Graph) -> bool:
        """
        Check if graph is a Minimal Obstruction Graph
        (connected graph with more than one cycle)
        """
        if not nx.is_connected(G):
            return False
        
        # Check if graph has more than one cycle
        # For connected graph: cycles = |E| - |V| + 1
        n_vertices = G.number_of_nodes()
        n_edges = G.number_of_edges()
        cycles = n_edges - n_vertices + 1
        
        return cycles > 1
    
    @staticmethod
    def is_rmog_graph(G: nx.Graph) -> bool:
        """
        Check if graph is a Relaxed Minimal Obstruction Graph
        (MOG, simple path, or path with one extra edge)
        """
        if not nx.is_connected(G):
            return False
        
        n_vertices = G.number_of_nodes()
        n_edges = G.number_of_edges()
        cycles = n_edges - n_vertices + 1
        
        # MOG: cycles > 1
        # Path: cycles == 0 and n_edges == n_vertices - 1
        # Path with one extra edge: cycles == 1
        
        if cycles > 1:  # MOG
            return True
        
        if cycles == 0:  # Path
            return n_edges == n_vertices - 1
        
        if cycles == 1:  # Path with one extra edge
            return True
        
        return False
    
    @staticmethod
    def count_subgraphs_with_property(S: List[int], hash_func, 
                                     property_func, d: int = 2) -> int:
        """
        Count subgraphs of G(S, h) with given property
        """
        G = GraphAnalyzer.build_graph(S, hash_func, d)
        count = 0
        
        # Check all subgraphs
        nodes = list(G.nodes())
        for i in range(1, 2**len(nodes)):
            if i >= 2**len(nodes):
                break
            
            # Get subset of nodes
            subset = []
            for j in range(len(nodes)):
                if i & (1 << j):
                    subset.append(nodes[j])
            
            if len(subset) < 2:
                continue
            
            subgraph = G.subgraph(subset)
            if property_func(subgraph):
                count += 1
        
        return count


class CuckooHashingAnalyzer:
    """
    Analyzes cuckoo hashing properties
    """
    
    def __init__(self, m: int, ell: int, c: int = 1, epsilon: float = 0.1):
        self.m = m
        self.ell = ell
        self.c = c
        self.epsilon = epsilon
        
    def is_suitable(self, hash_func) -> bool:
        """
        Check if hash function pair is suitable for cuckoo hashing
        """
        # For cuckoo hashing, suitable means every component has at most one cycle
        # This is equivalent to no MOG subgraph
        
        # We'll use the graph analyzer to check
        G = GraphAnalyzer.build_graph([], hash_func)  # Need to pass S
        return not GraphAnalyzer.is_mog_graph(G)
    
    def analyze_success_probability(self, S: List[int], 
                                   num_trials: int = 1000) -> float:
        """
        Estimate success probability for cuckoo hashing
        """
        successes = 0
        
        for _ in range(num_trials):
            # Create hash function from Z class
            hash_func = ZHashClass(self.m, self.ell, self.c, d=2)
            
            # Build graph
            G = GraphAnalyzer.build_graph(S, hash_func, d=2)
            
            # Check if suitable (no MOG subgraphs)
            suitable = True
            for comp in nx.connected_components(G):
                subgraph = G.subgraph(comp)
                if GraphAnalyzer.is_mog_graph(subgraph):
                    suitable = False
                    break
            
            if suitable:
                successes += 1
        
        return successes / num_trials


class LoadBalancingAnalyzer:
    """
    Analyzes load balancing properties
    """
    
    @staticmethod
    def calculate_bin_loads(S: List[int], hash_func) -> Dict[int, int]:
        """
        Calculate loads of bins for d=1 case
        """
        loads = defaultdict(int)
        hash_values = hash_func.hash_set(S)
        
        # For d=1, hash_tuple returns a single value
        for x, vals in hash_values.items():
            if len(vals) >= 1:
                loads[vals[0]] += 1
        
        return dict(loads)
    
    @staticmethod
    def calculate_two_choice_loads(S: List[int], hash_func) -> Dict[int, int]:
        """
        Calculate loads for two-choice load balancing (d=2)
        Each key chooses the bin with smaller load
        """
        loads = defaultdict(int)
        hash_values = hash_func.hash_set(S)
        
        for x, (v1, v2) in hash_values.items():
            # Choose bin with smaller load
            if loads[v1] <= loads[v2]:
                loads[v1] += 1
            else:
                loads[v2] += 1
        
        return dict(loads)
    
    @staticmethod
    def compute_max_load(S: List[int], hash_func, d: int = 2) -> int:
        """Compute maximum bin load"""
        if d == 1:
            loads = LoadBalancingAnalyzer.calculate_bin_loads(S, hash_func)
        else:
            loads = LoadBalancingAnalyzer.calculate_two_choice_loads(S, hash_func)
        
        return max(loads.values()) if loads else 0


def main():
    """Example usage of the implemented classes"""
    
    print("=" * 60)
    print("Hash Class Z - Implementation Example")
    print("=" * 60)
    
    # Parameters
    n = 100  # Number of keys
    m = 110  # Hash table size (slightly larger than n)
    ell = 10  # Range of g-functions
    c = 2  # Number of g-functions
    d = 2  # Number of hash functions
    
    print(f"\nParameters:")
    print(f"  n = {n} (keys)")
    print(f"  m = {m} (hash table size)")
    print(f"  ell = {ell}")
    print(f"  c = {c}")
    print(f"  d = {d}")
    
    # Generate random keys
    S = list(range(n))
    
    # Create hash function from Z class
    print("\nCreating hash function from Z class...")
    hash_func = ZHashClass(m, ell, c, d)
    
    # Demonstrate hashing
    print("\nHashing first 5 keys:")
    for x in S[:5]:
        h_tuple = hash_func.hash_tuple(x)
        print(f"  h({x}) = {h_tuple}")
    
    # Check deficiency for a set
    T = S[:5]
    deficiency = hash_func.get_deficiency(T)
    print(f"\nDeficiency for T = {T[:5]}...: {deficiency}")
    print(f"  T-good: {hash_func.is_good(T)}")
    print(f"  T-bad: {hash_func.is_bad(T)}")
    print(f"  T-critical: {hash_func.is_critical(T)}")
    
    # Build graph
    print("\nBuilding graph from hash values...")
    G = GraphAnalyzer.build_graph(S, hash_func, d=2)
    print(f"  Nodes: {G.number_of_nodes()}")
    print(f"  Edges: {G.number_of_edges()}")
    print(f"  Connected components: {nx.number_connected_components(G)}")
    
    # Find components and check for MOG subgraphs
    print("\nAnalyzing graph components:")
    mog_count = 0
    for i, comp in enumerate(nx.connected_components(G)):
        subgraph = G.subgraph(comp)
        is_mog = GraphAnalyzer.is_mog_graph(subgraph)
        if is_mog:
            mog_count += 1
        nodes = len(comp)
        edges = subgraph.number_of_edges()
        cycles = edges - nodes + 1
        print(f"  Component {i+1}: {nodes} nodes, {edges} edges, "
              f"{cycles} cycles, MOG: {is_mog}")
    
    print(f"\nTotal MOG subgraphs found: {mog_count}")
    
    # Check if suitable for cuckoo hashing
    suitable = mog_count == 0
    print(f"\nSuitable for cuckoo hashing: {suitable}")
    
    # Analyze load balancing
    print("\nLoad balancing analysis:")
    loads = LoadBalancingAnalyzer.calculate_two_choice_loads(S, hash_func)
    if loads:
        max_load = max(loads.values())
        avg_load = sum(loads.values()) / len(loads)
        print(f"  Max bin load: {max_load}")
        print(f"  Average bin load: {avg_load:.2f}")
        print(f"  Number of non-empty bins: {len(loads)}")
    
    # Create fully random hash for comparison
    print("\nComparing with fully random hash function:")
    random_hash = RandomHashSimulator(m, d)
    
    # Compare hash values for a few keys
    print("  Hash values comparison:")
    for x in S[:5]:
        z_hash = hash_func.hash_tuple(x)
        r_hash = random_hash.hash_tuple(x)
        print(f"    x={x}: Z={z_hash}, Random={r_hash}")
    
    print("\n" + "=" * 60)
    print("Implementation complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()